### ISSUE TITLE
Flash-PSRAM

### ISSUE THREAD

**Issue by GlebDen** [gregdavill/obsidian-boa#6]
Hello. 
First of all I would like to thank you for the excellent work.
I would like to clarify one point. In your schematic, external memory is W25Q32JVSS (U2 and U4). But in the picture of pcb these are different cases. Perhaps there is an error in the circuit and something like ESP-PSRAM64H was meant ??
I would be grateful for clarifications! Thank you.

**Comment by gregdavill** [comment]
Thanks, you're right. 

It's a FLASH U4 and PSRAM U2. 

Any PSRAM compatible with the ESP32 can be used. I'm using 
these because they seem to be the easiest to get: https://lcsc.com/product-detail/RAM_Lyontek-Inc-LY68L6400SLIT_C261881.html

A small oversight I've updated the schematic with correct part numbers
